\"\"\"Minimal LightZero-like integration demo using the MuZeroAdapter + PUCT.\n+\n+This script demonstrates a simple planning loop:\n+ - wrap a model with MuZeroAdapter\n+ - run PUCT to choose an action from the root\n+ - apply the action to a simple deterministic environment (1D position)\n+ - repeat for a small horizon\n+\n+The goal is to show the mapping between a MuZero-style adapter and MCTS search.\n+\"\"\"\n+from typing import Any\n+import argparse\n+import random\n+import numpy as np\n+import torch\n+\n+from src.mcts.puct import PUCT\n+from src.mcts.nn_model import SmallDiscreteModel\n+from src.crosshq.mcts_adapter import CrossHQMCTSAdapter\n+from paperAssignments.Assignments1_50.CA5.integrations.lightzero_adapter import MuZeroAdapter  # noqa: E402\n+\n+\n+class SimpleEnv:\n+    def __init__(self, goal: int = 3):\n+        self.goal = goal\n+        self.state = 0\n+\n+    def step(self, action_idx: int):\n+        # map idx 0->-1,1->0,2->+1\n+        delta = action_idx - 1\n+        self.state += delta\n+        reward = 1.0 if self.state == self.goal else 0.0\n+        done = self.state == self.goal\n+        return self.state, reward, done\n+\n+\n+def run_planning(seed: int = 0, sims: int = 50, horizon: int = 5):\n+    random.seed(seed)\n+    np.random.seed(seed)\n+    torch.manual_seed(seed)\n+\n+    # small learned model\n+    model = SmallDiscreteModel(n_actions=3, hidden=64)\n+    adapter = MuZeroAdapter(model)\n+\n+    action_space = [0, 1, 2]\n+    puct = PUCT(adapter, action_space=action_space, c_puct=1.0, dirichlet_alpha=0.3)\n+\n+    env = SimpleEnv(goal=3)\n+\n+    for t in range(horizon):\n+        root = puct.search(env.state, num_simulations=sims)\n+        # pick best by visits\n+        best_idx = max(root.children.items(), key=lambda kv: kv[1].visits)[0]\n+        state, reward, done = env.step(best_idx)\n+        print(f\"t={t} chosen={best_idx} state={state} reward={reward} done={done}\")\n+        if done:\n+            break\n+\n+\n+if __name__ == \"__main__\":\n+    parser = argparse.ArgumentParser()\n+    parser.add_argument(\"--seed\", type=int, default=0)\n+    parser.add_argument(\"--sims\", type=int, default=50)\n+    parser.add_argument(\"--horizon\", type=int, default=5)\n+    args = parser.parse_args()\n+    run_planning(seed=args.seed, sims=args.sims, horizon=args.horizon)\n+\n*** End Patch**Please respond with the next message.**"}},]}]}]}











