# src/config.py

import os

class CA16Config:
    # General
    SEED = 42
    DEVICE = "cuda" if os.getenv("CUDA_VISIBLE_DEVICES", None) else "cpu"
    OUTPUT_DIR = "results"
    
    # Training
    BATCH_SIZE = 64
    LEARNING_RATE = 1e-4
    NUM_EPOCHS = 100
    GRADIENT_ACCUMULATION_STEPS = 1
    STATE_LOSS_WEIGHT = 1.0
    RETURN_LOSS_WEIGHT = 1.0
    
    # Model
    TRANSFORMER_DIM = 128
    NUM_HEADS = 4
    NUM_LAYERS = 2
    DROPOUT = 0.1
    
    # Environment
    ENV_NAME = "MultiModalGridWorld-v0"
    ENV_SIZE = 6
    NUM_GOALS = 2
    NUM_OBSTACLES = 3
    ENV_STEPS = 50

    # Neurosymbolic
    SYMBOLIC_WEIGHT = 0.5
    SYMBOLIC_FEATURE_DIM = 8
    NEURO_HIDDEN_DIM = 32

    # Continual Learning
    EWC_LAMBDA = 1000
    CL_HIDDEN_DIM = 64
    CL_EPISODES_PER_TASK = 20
    NUM_TASKS = 3

    # Meta-Learning
    MAML_HIDDEN_DIM = 32
    MAML_INNER_LR = 0.01
    MAML_META_LR = 0.001
    MAML_ADAPTATION_STEPS = 5

    # Human-AI Collaboration
    PREFERENCE_MODEL_LR = 1e-3
    COLLAB_HIDDEN_DIM = 32
    COLLABORATION_THRESHOLD = 0.7
    PREFERENCE_HIDDEN_DIM = 32
    TRUST_HIDDEN_DIM = 64

    # Advanced Computing
    QUANTUM_NUM_QUBITS = 4
    QUANTUM_NUM_LAYERS = 2
    NEUROMORPHIC_HIDDEN_DIM = 128
    NEUROMORPHIC_NUM_LAYERS = 2
    NEUROMORPHIC_TIME_STEPS = 5
    FEDERATED_NUM_CLIENTS = 5

    # Deployment
    SAFETY_THRESHOLD = 0.9
    PROD_HIDDEN_DIM = 32
    SAFETY_INFERENCE_TIME_THRESHOLD = 0.1
    SAFETY_MEMORY_USAGE_THRESHOLD = 0.8
    ETHICS_BIAS_THRESHOLD = 0.1
    ETHICS_FAIRNESS_THRESHOLD = 0.8

    # Visualizations
    NUM_ATTENTION_HEADS_TO_PLOT = 4
    MAX_FEATURE_SAMPLES = 1000
    MAX_FEATURE_CORRELATION_SAMPLES = 50

    # Video Generation
    VIDEO_OUTPUT_DIR = "videos"
    VIDEO_FPS = 24
    VIDEO_FRAME_WIDTH = 1920
    VIDEO_FRAME_HEIGHT = 1080
    VIDEO_DPI = 100
    AGENT_RADIUS = 0.3
    GOAL_RADIUS = 0.3
    VIDEO_TOTAL_EPISODES = 50
    VIDEO_FRAMES_PER_EPISODE = 20
    VIDEO_ACTION_UPDATE_FREQ = 5
    NEURAL_FEATURES_TO_PLOT = 10
    SYMBOLIC_FEATURES_TO_PLOT = 8
    TRUST_BETA_ALPHA = 6
    TRUST_BETA_BETA = 1
    RECENT_STEPS_PLOT = 20
    FORGETTING_MAGNITUDE = 0.3
    FORGETTING_SMOOTHING_WINDOW = 5
    VIDEO_TOTAL_FRAMES = 300
    NUM_TASKS_COMPOSITE_VIDEO = 4
    TRUST_BETA_ALPHA_MULTIPLIER = 5
    TRUST_BETA_BETA_CONF = 2
    TRUST_BETA_ALPHA_MULTIPLIER_CONF = 3
    STATE_DIM = 8
    ACTION_DIM = 4
    SEQ_LEN = 5
    CONTEXT_LENGTH = 5
    QUERY_LENGTH = 10
    SCALING_MODEL_SIZES = [32, 64, 128, 256, 512]
    SCALING_PERFORMANCES = [0.5, 0.65, 0.75, 0.82, 0.87]
    SCALING_DATASET_SIZES = [1000, 5000, 10000, 50000, 100000]
    EWC_HIDDEN_DIM = 128
    PROG_NET_HIDDEN_DIMS = [64, 64]
    PROG_NET_INITIAL_COLUMNS = 3
    PROG_NET_NEW_COLUMNS = 2

config = CA16Config()
